---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
spec:
  ports:
    - protocol: TCP
      name: nginx
      port: 80
      targetPort: 80
  selector:
    app: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: backend-multitool
spec:
  ports:
    - protocol: TCP
      name: multitool
      port: 80
      targetPort: 80
  selector:
    app: multitool

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netology-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: cicd-tools.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-nginx
                port:
                  name: nginx
          - path: /api
            pathType: Exact
            backend:
              service:
                name: backend-multitool
                port:
                  name: multitool